conservative_compressible_pointer – FORESEER
conservative_compressible_pointer Function
13 statements
Source File
public function conservative_compressible_pointer(to, error_message) result(pointer_)
Return conservative_compressible pointer associated to conservative_object or its extensions until conservative_compressible included.
Note
A type-guard check is performed and error stop is raised if necessary.
Arguments
Type Intent Optional Attributes Name
class(conservative_object), intent(in), target :: to
Target of associate.
character(len=*), intent(in), optional :: error_message
Auxiliary error message.
Return Value class(conservative_compressible), pointer
Associated pointer.
Called By
Source Code
conservative_compressible_pointer
Source Code
   function conservative_compressible_pointer(to, error_message) result(pointer_)
   !< Return [[conservative_compressible]] pointer associated to [[conservative_object]] or its extensions until
   !< [[conservative_compressible]] included.
   !<
   !< @note A type-guard check is performed and error stop is raised if necessary.
   class(conservative_object), intent(in), target   :: to            !< Target of associate.
   character(*),               intent(in), optional :: error_message !< Auxiliary error message.
   class(conservative_compressible), pointer        :: pointer_      !< Associated pointer.
   select type(to)
   type is(conservative_compressible)
      pointer_ => to
   class default
      write(stderr, '(A)') 'error: cast conservative_object to conservative_compressible failed!'
      if (present(error_message)) write(stderr, '(A)') error_message
      stop
   endselect
   endfunction conservative_compressible_pointer
All Procedures
add add add_euler array array compute_derivate compute_dt compute_fluxes compute_fluxes compute_fluxes_from_primitive compute_post_rarefaction compute_post_shock compute_states23_from_u23 compute_u23 compute_up23 compute_waves compute_waves compute_waves compute_waves compute_waves_u23 compute_waves_up23 cons_assign_cons cons_divide_real cons_multiply_cons cons_multiply_real conservative_compressible conservative_compressible_instance conservative_compressible_pointer conservative_to_primitive_compressible cp cv delta density description description description description destroy destroy destroy dEuler_dt energy energy eos_assign_eos eos_compressible eos_compressible_instance eta euler_assign_euler euler_assign_real euler_local_error euler_multiply_euler euler_multiply_real g gm1 gp1 impose_boundary_conditions initialize initialize initialize initialize initialize initialize initialize initialize left_eigenvectors momentum negative negative output parse_command_line_interface positive positive pressure pressure prim_assign_prim prim_divide_real prim_multiply_prim prim_multiply_real primitive_compressible primitive_compressible_instance primitive_compressible_pointer primitive_to_conservative_compressible R real_multiply_cons real_multiply_euler real_multiply_prim reconstruct_interfaces_characteristic reconstruct_interfaces_conservative reconstruct_interfaces_primitive riemann_solver_exact riemann_solver_hllc riemann_solver_llf riemann_solver_pvl right_eigenvectors save_time_serie set_states14 solve solve solve solve solve_u23 solve_up23 speed_of_sound sub sub sub_euler temperature velocity
Call graph
solve calls conservative_compressible_pointer
foreseer_test_conservative_compressible calls conservative_compressible_pointer