errored – FORESEER
errored Subroutine
92 statements
Source File
private subroutine errored(self, error, pref, switch, val_str, log_value)
Trig error occurence and print meaningful message.
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
integer(kind=I4P), intent(in) :: error
Error occurred.
character(len=*), intent(in), optional :: pref
Prefixing string.
character(len=*), intent(in), optional :: switch
CLA switch name.
character(len=*), intent(in), optional :: val_str
Value string.
character(len=*), intent(in), optional :: log_value
Logical value to be casted.
Calls
Source Code
errored
Source Code
  subroutine errored(self, error, pref, switch, val_str, log_value)
  !< Trig error occurence and print meaningful message.
  class(command_line_argument), intent(inout) :: self      !< CLA data.
  integer(I4P),                 intent(in)    :: error     !< Error occurred.
  character(*), optional,       intent(in)    :: pref      !< Prefixing string.
  character(*), optional,       intent(in)    :: switch    !< CLA switch name.
  character(*), optional,       intent(in)    :: val_str   !< Value string.
  character(*), optional,       intent(in)    :: log_value !< Logical value to be casted.
  character(len=:), allocatable               :: prefd     !< Prefixing string.
  self%error = error
  if (self%error/=0) then
    prefd = '' ; if (present(pref)) prefd = pref
    prefd = prefd//self%progname//': '//colorize('error', color_fg=self%error_color, style=self%error_style)
    select case(self%error)
    case(ERROR_OPTIONAL_NO_DEF)
      if (self%is_positional) then
        self%error_message = prefd//': "'//trim(str(n=self%position))//'-th" positional option has not a default value!'
      else
        self%error_message = prefd//': named option "'//self%switch//'" has not a default value!'
      endif
    case(ERROR_REQUIRED_M_EXCLUDE)
      self%error_message = prefd//': named option "'//self%switch//'" cannot exclude others'//&
                           ', it being required, only optional ones can!'
    case(ERROR_POSITIONAL_M_EXCLUDE)
      self%error_message = prefd//': "'//trim(str(n=self%position))//&
                           '-th" positional option cannot exclude others, only optional named options can!'
    case(ERROR_NAMED_NO_NAME)
      self%error_message = prefd//': a non positional optiona must have a switch name!'
    case(ERROR_POSITIONAL_NO_POSITION)
      self%error_message = prefd//': a positional option must have a position number different from 0!'
    case(ERROR_POSITIONAL_NO_STORE)
      self%error_message = prefd//': a positional option must have action set to "'//action_store//'"!'
    case(ERROR_M_EXCLUDE)
      self%error_message = prefd//': the options "'//self%switch//'" and "'//self%m_exclude//&
                           '" are mutually exclusive, but both have been passed!'
    case(ERROR_NOT_IN_CHOICES)
      if (self%is_positional) then
        self%error_message = prefd//': value of "'//trim(str(n=self%position))//&
                             '-th" positional option must be chosen in:'
      else
        self%error_message = prefd//': value of named option "'//self%switch//'" must be chosen in: '
      endif
      self%error_message = self%error_message//'('//self%choices//')'
      self%error_message = self%error_message//' but "'//trim(val_str)//'" has been passed!'
    case(ERROR_MISSING_REQUIRED)
      if (.not.self%is_positional) then
        self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//'" is required!'
      else
        self%error_message = prefd//': "'//trim(str(self%position, .true.))//'-th" positional option is required!'
      endif
    case(ERROR_CASTING_LOGICAL)
      self%error_message = prefd//': cannot convert "'//log_value//'" of option "'//self%switch//'" to logical type!'
    case(ERROR_CHOICES_LOGICAL)
      self%error_message = prefd//': cannot use "choices" value check for option "'//self%switch//&
                           '" it being of logical type! The choices are limited to ".true." or ".false." by definition!'
    case(ERROR_NO_LIST)
      if (.not.self%is_positional) then
        self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//&
                             '" has not "nargs" value but an array has been passed to "get" method!'
      else
        self%error_message = prefd//': "'//trim(str(self%position, .true.))//'-th" positional option '//&
                             'has not "nargs" value but an array has been passed to "get" method!'
      endif
    case(ERROR_NARGS_INSUFFICIENT)
      if (.not.self%is_positional) then
        if (self%nargs=='+') then
          self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//&
                               '" requires at least 1 argument but no one remains!'
        else
          self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//'" requires '//&
                               trim(adjustl(self%nargs))//' arguments but no enough ones remain!'
        endif
      else
        if (self%nargs=='+') then
          self%error_message = prefd//': "'//trim(str(self%position, .true.))//&
                               '-th" positional option requires at least 1 argument but no one remains'
        else
          self%error_message = prefd//': "'//trim(str(self%position, .true.))//'-th" positional option requires '//&
                               trim(adjustl(self%nargs))//' arguments but no enough ones remain!'
        endif
      endif
    case(ERROR_VALUE_MISSING)
      self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//'" needs a value that is not passed!'
    case(ERROR_UNKNOWN)
      self%error_message = prefd//': switch "'//trim(adjustl(switch))//'" is unknown!'
    case(ERROR_ENVVAR_POSITIONAL)
      self%error_message = prefd//': "'//trim(str(self%position, .true.))//'-th" positional option '//&
                           'has "envvar" value that is not allowed for positional option!'
    case(ERROR_ENVVAR_NOT_STORE)
      self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//&
                           '" is an envvar with action different from "'//action_store//'" that is not allowed!'
    case(ERROR_ENVVAR_NARGS)
      self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//&
                           '" is an envvar that is not allowed for list valued option!'
    case(ERROR_STORE_STAR_POSITIONAL)
      self%error_message = prefd//': "'//trim(str(self%position, .true.))//'-th" positional option '//&
                           'has "'//action_store_star//'" action that is not allowed for positional option!'
    case(ERROR_STORE_STAR_NARGS)
      self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//&
                           '" has "'//action_store_star//'" action that is not allowed for list valued option!'
    case(ERROR_STORE_STAR_ENVVAR)
      self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//&
                           '" has "'//action_store_star//'" action that is not allowed for environment variable option!'
    case(ERROR_ACTION_UNKNOWN)
      self%error_message = prefd//': named option "'//trim(adjustl(self%switch))//'" has unknown "'//self%act//'" action!'
    endselect
    call self%print_error_message
  endif
  endsubroutine errored
All Procedures
add add add add add_euler add_group array array assign_object bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check check check check_action_consistency check_choices check_endian check_envvar_consistency check_list_size check_m_exclude_consistency check_m_exclusive check_m_exclusive check_named_consistency check_optional_consistency check_positional_consistency cla_assign_cla clasg_assign_clasg cli_assign_cli color_index colorize colors_samples compact_real_string compute compute compute compute compute compute compute compute_dt compute_fluxes compute_fluxes compute_fluxes_from_primitive compute_p23 compute_u23 compute_up23 compute_waves compute_waves compute_waves_u23 compute_waves_up23 cons_assign_cons cons_divide_real cons_multiply_cons cons_multiply_real conservative_compressible conservative_compressible_instance conservative_compressible_pointer conservative_to_primitive_compressible count count_substring cp create create create create create create create create create create create create create create create_ create_alpha_object create_alpha_object_constructor create_base_object_constructor create_beta_object create_beta_object_constructor create_constructor create_constructor create_constructor create_constructor create_constructor create_constructor create_interpolations_object create_interpolations_object_constructor create_interpolator create_interpolator_object create_interpolator_object_constructor create_kappa_object create_kappa_object_constructor create_weights_object create_weights_object_constructor ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P cv density description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_ dEuler_dt digit digit_I1 digit_I2 digit_I4 digit_I8 energy energy eos_compressible eos_compressible_instance errored errored errored euler_assign_euler euler_assign_real euler_local_error euler_multiply_euler euler_multiply_real finalize finalize finalize free free free free_object gam get_args_from_invocation get_args_from_string get_cla get_cla get_cla_from_buffer get_cla_list get_cla_list get_cla_list_from_buffer get_cla_list_varying_char get_cla_list_varying_char get_cla_list_varying_I1P get_cla_list_varying_I1P get_cla_list_varying_I2P get_cla_list_varying_I2P get_cla_list_varying_I4P get_cla_list_varying_I4P get_cla_list_varying_I8P get_cla_list_varying_I8P get_cla_list_varying_logical get_cla_list_varying_logical get_cla_list_varying_R16P get_cla_list_varying_R16P get_cla_list_varying_R4P get_cla_list_varying_R4P get_cla_list_varying_R8P get_cla_list_varying_R8P get_clasg_indexes impose_boundary_conditions init init init init init init init init init initialize initialize initialize initialize initialize initialize integrate integrate integrate integrate integrate integrate integrate integrate integrate interpolate_debug interpolate_debug interpolate_standard interpolate_standard is_admissible is_called_group is_defined is_defined is_defined_group is_parsed is_passed is_passed is_required_passed is_required_passed is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported left_eigenvectors max_stages max_stages max_stages max_stages_steps max_steps max_steps max_steps max_steps max_steps min_stages min_stages min_stages min_stages_steps min_steps min_steps min_steps min_steps min_steps momentum negative negative new_Dt output parse parse parse_command_line_interface penf_init penf_print positive positive pressure pressure prim_assign_prim prim_divide_real prim_multiply_prim prim_multiply_real primitive_compressible primitive_compressible_instance primitive_compressible_pointer primitive_to_conservative_compressible print_error_message print_usage print_version R raise_error_m_exclude raise_error_m_exclude raise_error_nargs_insufficient raise_error_switch_unknown raise_error_value_missing real_multiply_cons real_multiply_euler real_multiply_prim reconstruct_interfaces_characteristic reconstruct_interfaces_conservative reconstruct_interfaces_primitive replace replace_all riemann_solver_llf riemann_solver_pvl right_eigenvectors sanitize_defaults sanitize_defaults save_man_page save_time_serie save_usage_to_markdown set_mutually_exclusive_groups set_states14 signature signature signature smoothness_indicators solve solve solve_u23 solve_up23 speed_of_sound str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P style_index styles_samples sub sub sub_euler tau temperature tokenize tokenize unique update_previous update_previous update_previous upper upper_case usage usage usage used_registers velocity weno_exp weno_odd wenoof_create wstrip
Call graph
errored calls str, colorize
str calls strf_i4p, str_r4p, str_a_i4p, strf_i2p, strf_i1p, strf_r4p, str_a_r8p, strf_i8p, str_a_i2p, str_a_r4p, str_i4p, str_a_i1p, str_i2p, strf_r8p, str_i8p, str_a_i8p, str_bol, str_i1p, str_r8p
colorize calls style_index, color_index, upper
str_r4p calls compact_real_string
str_a_i4p calls str_i4p
str_a_r8p calls str_r8p
str_a_i2p calls str_i2p
str_a_r4p calls str_r4p
str_a_i1p calls str_i1p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string