usage – FORESEER
usage Function
116 statements
Source File
private function usage(self, pref, markdown)
Get correct usage.
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(in) :: self
CLAs group data.
character(len=*), intent(in), optional :: pref
Prefixing string.
logical, intent(in), optional :: markdown
Format for markdown
Return Value character(len=:), allocatable
Usage string.
Calls
Source Code
usage
Source Code
  function usage(self, pref, markdown)
  !< Get correct usage.
  class(command_line_argument), intent(in) :: self       !< CLAs group data.
  character(*), optional,       intent(in) :: pref       !< Prefixing string.
  logical,      optional,       intent(in) :: markdown   !< Format for markdown
  character(len=:), allocatable            :: usage      !< Usage string.
  character(len=:), allocatable            :: prefd      !< Prefixing string.
  character(len=:), allocatable            :: switch_    !< Switch name, local variable.
  character(len=:), allocatable            :: switch_ab_ !< Abbreviated switch name, local variable.
  integer(I4P)                             :: a          !< Counter.
  logical                                  :: markdownd  !< Format for markdown
  integer                                  :: indent     !< how many spaces to indent
  markdownd = .false. ; if (present(markdown)) markdownd = markdown
  indent = 4
  switch_ = colorize(trim(adjustl(self%switch)), color_fg=self%help_color, style=self%help_style)
  switch_ab_ = colorize(trim(adjustl(self%switch_ab)), color_fg=self%help_color, style=self%help_style)
  if (.not.self%is_hidden) then
    if (self%act==action_store) then
      if (.not.self%is_positional) then
        if (allocated(self%nargs)) then
          usage = ''
          select case(self%nargs)
          case('+')
            usage = usage//' value#1 [value#2...]'
          case('*')
            usage = usage//' [value#1 value#2...]'
          case default
            do a=1, cton(str=trim(adjustl(self%nargs)),knd=1_I4P)
              usage = usage//' value#'//trim(str(a, .true.))
            enddo
          endselect
          if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//usage//'`, `'//trim(adjustl(self%switch_ab))//usage//'`'
            else
              usage = '   '//switch_//usage//', '//switch_ab_//usage
            endif
          else
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//usage//'`'
            else
              usage = '   '//switch_//usage
            endif
          endif
        else
          if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//' value`, `'//trim(adjustl(self%switch_ab))//' value'//'`'
            else
              usage = '   '//switch_//' value, '//switch_ab_//' value'
            endif
          else
            if (markdownd) then
              usage = new_line('a')//'* `'//trim(adjustl(self%switch))//' value`'
            else
              usage = '   '//switch_//' value'
            endif
          endif
        endif
      else
        usage = '  value'
      endif
      if (allocated(self%choices)) then
        usage = usage//', value in: `'//self%choices//'`'
      endif
    elseif (self%act==action_store_star) then
      usage = '  [value]'
      if (allocated(self%choices)) then
        usage = usage//', value in: ('//self%choices//')'
      endif
    else
      if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
        if (markdownd) then
          usage = new_line('a')//'* `'//trim(adjustl(self%switch))//'`, `'//trim(adjustl(self%switch_ab))//'`'
        else
          usage = '   '//switch_//', '//switch_ab_
        endif
      else
        if (markdownd) then
          usage = new_line('a')//'* `'//trim(adjustl(self%switch))//'`'
        else
          usage = '   '//switch_
        endif
      endif
    endif
    prefd = '' ; if (present(pref)) prefd = pref
    usage = prefd//usage
    if (self%is_positional) usage = usage//new_line('a')//prefd//repeat(' ',indent)//trim(str(self%position, .true.))//&
      '-th argument'
    if (allocated(self%envvar)) then
      if (self%envvar /= '') then
        usage = usage//new_line('a')//prefd//repeat(' ',10)//'environment variable name "'//trim(adjustl(self%envvar))//'"'
      endif
    endif
    if (.not.self%is_required) then
      if (self%def /= '') then
        if (markdownd) then
          ! two spaces make a line break in markdown.
          usage = usage//'  '//new_line('a')//prefd//repeat(' ', 4)//'default value '//trim(replace_all(self%def,ARGS_SEP,' '))
        else
          usage = usage//new_line('a')//prefd//repeat(' ', indent)//'default value '//trim(replace_all(self%def,ARGS_SEP,' '))
        endif
      endif
    endif
    if (self%m_exclude/='') usage = usage//new_line('a')//prefd//repeat(' ', indent)//'mutually exclude "'//self%m_exclude//'"'
    if (markdownd) then
      usage = usage//'  '//new_line('a')//prefd//repeat(' ',4)//trim(adjustl(self%help))
      if (self%help_markdown/='') then
        usage = usage//trim(adjustl(self%help_markdown))
      endif
    else
      usage = usage//new_line('a')//prefd//repeat(' ', indent)//trim(adjustl(self%help))
    endif
  else
    usage = ''
  endif
  endfunction usage
All Procedures
add add add add add_euler add_group array array assign_object bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check check check check_action_consistency check_choices check_endian check_envvar_consistency check_list_size check_m_exclude_consistency check_m_exclusive check_m_exclusive check_named_consistency check_optional_consistency check_positional_consistency cla_assign_cla clasg_assign_clasg cli_assign_cli color_index colorize colors_samples compact_real_string compute compute compute compute compute compute compute compute_dt compute_fluxes compute_fluxes compute_fluxes_from_primitive compute_p23 compute_u23 compute_up23 compute_waves compute_waves compute_waves_u23 compute_waves_up23 cons_assign_cons cons_divide_real cons_multiply_cons cons_multiply_real conservative_compressible conservative_compressible_instance conservative_compressible_pointer conservative_to_primitive_compressible count count_substring cp create create create create create create create create create create create create create create create_ create_alpha_object create_alpha_object_constructor create_base_object_constructor create_beta_object create_beta_object_constructor create_constructor create_constructor create_constructor create_constructor create_constructor create_constructor create_interpolations_object create_interpolations_object_constructor create_interpolator create_interpolator_object create_interpolator_object_constructor create_kappa_object create_kappa_object_constructor create_weights_object create_weights_object_constructor ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P cv density description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_ dEuler_dt digit digit_I1 digit_I2 digit_I4 digit_I8 energy energy eos_compressible eos_compressible_instance errored errored errored euler_assign_euler euler_assign_real euler_local_error euler_multiply_euler euler_multiply_real finalize finalize finalize free free free free_object gam get_args_from_invocation get_args_from_string get_cla get_cla get_cla_from_buffer get_cla_list get_cla_list get_cla_list_from_buffer get_cla_list_varying_char get_cla_list_varying_char get_cla_list_varying_I1P get_cla_list_varying_I1P get_cla_list_varying_I2P get_cla_list_varying_I2P get_cla_list_varying_I4P get_cla_list_varying_I4P get_cla_list_varying_I8P get_cla_list_varying_I8P get_cla_list_varying_logical get_cla_list_varying_logical get_cla_list_varying_R16P get_cla_list_varying_R16P get_cla_list_varying_R4P get_cla_list_varying_R4P get_cla_list_varying_R8P get_cla_list_varying_R8P get_clasg_indexes impose_boundary_conditions init init init init init init init init init initialize initialize initialize initialize initialize initialize integrate integrate integrate integrate integrate integrate integrate integrate integrate interpolate_debug interpolate_debug interpolate_standard interpolate_standard is_admissible is_called_group is_defined is_defined is_defined_group is_parsed is_passed is_passed is_required_passed is_required_passed is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported left_eigenvectors max_stages max_stages max_stages max_stages_steps max_steps max_steps max_steps max_steps max_steps min_stages min_stages min_stages min_stages_steps min_steps min_steps min_steps min_steps min_steps momentum negative negative new_Dt output parse parse parse_command_line_interface penf_init penf_print positive positive pressure pressure prim_assign_prim prim_divide_real prim_multiply_prim prim_multiply_real primitive_compressible primitive_compressible_instance primitive_compressible_pointer primitive_to_conservative_compressible print_error_message print_usage print_version R raise_error_m_exclude raise_error_m_exclude raise_error_nargs_insufficient raise_error_switch_unknown raise_error_value_missing real_multiply_cons real_multiply_euler real_multiply_prim reconstruct_interfaces_characteristic reconstruct_interfaces_conservative reconstruct_interfaces_primitive replace replace_all riemann_solver_llf riemann_solver_pvl right_eigenvectors sanitize_defaults sanitize_defaults save_man_page save_time_serie save_usage_to_markdown set_mutually_exclusive_groups set_states14 signature signature signature smoothness_indicators solve solve solve_u23 solve_up23 speed_of_sound str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P style_index styles_samples sub sub sub_euler tau temperature tokenize tokenize unique update_previous update_previous update_previous upper upper_case usage usage usage used_registers velocity weno_exp weno_odd wenoof_create wstrip
Call graph
usage calls colorize, replace_all, str, cton
colorize calls color_index, upper, style_index
replace_all calls replace, wstrip
str calls strf_i1p, strf_i4p, str_a_i1p, str_a_i2p, str_i1p, str_i8p, str_r8p, str_bol, strf_r8p, str_a_r4p, str_i4p, str_r4p, str_a_i8p, str_i2p, strf_i2p, str_a_r8p, str_a_i4p, strf_r4p, strf_i8p
cton calls ctor_r8p, ctoi_i8p, ctoi_i1p, ctor_r4p, ctoi_i2p, ctoi_i4p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p
str_r4p calls compact_real_string
str_a_i8p calls str_i8p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p