str – FORESEER
str Interface
3 statements
Source File
public interface str
Convert number (real and integer) to string (number to string type casting).
Calls
Called By
Module Procedures
strf_R8P str_R8P strf_R4P str_R4P strf_I8P str_I8P strf_I4P str_I4P strf_I2P str_I2P strf_I1P str_I1P str_bol str_a_R8P str_a_R4P str_a_I8P str_a_I4P str_a_I2P str_a_I1P
Module Procedures
private elemental function strf_R8P(fm, n) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
real(kind=R8P), intent(in) :: n
Real to be converted.
Return Value character(len=DR8P)
Returned string containing input number.
private elemental function str_R8P(n, no_sign, compact) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
Real to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=DR8P)
Returned string containing input number.
private elemental function strf_R4P(fm, n) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
real(kind=R4P), intent(in) :: n
Real to be converted.
Return Value character(len=DR4P)
Returned string containing input number.
private elemental function str_R4P(n, no_sign, compact) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
Real to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=DR4P)
Returned string containing input number.
private elemental function strf_I8P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I8P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI8P)
Returned string containing input number.
private elemental function str_I8P(n, no_sign) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI8P)
Returned string containing input number plus padding zeros.
private elemental function strf_I4P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I4P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI4P)
Returned string containing input number.
private elemental function str_I4P(n, no_sign) result(str)
Converting integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI4P)
Returned string containing input number plus padding zeros.
private elemental function strf_I2P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I2P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI2P)
Returned string containing input number.
private elemental function str_I2P(n, no_sign) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI2P)
Returned string containing input number plus padding zeros.
private elemental function strf_I1P(fm, n) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I1P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI1P)
Returned string containing input number.
private elemental function str_I1P(n, no_sign) result(str)
Convert integer to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI1P)
Returned string containing input number plus padding zeros.
private elemental function str_bol(n) result(str)
Convert logical to string.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n
Logical to be converted.
Return Value character(len=1)
Returned string containing input number plus padding zeros.
private pure function str_a_R8P(n, no_sign, separator, delimiters, compact) result(str)
Convert real array to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_R4P(n, no_sign, separator, delimiters, compact) result(str)
Convert real array to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I8P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I4P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I2P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
private pure function str_a_I1P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
All Procedures
add add add add add_euler add_group array array assign_object bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check check check check_action_consistency check_choices check_endian check_envvar_consistency check_list_size check_m_exclude_consistency check_m_exclusive check_m_exclusive check_named_consistency check_optional_consistency check_positional_consistency cla_assign_cla clasg_assign_clasg cli_assign_cli color_index colorize colors_samples compact_real_string compute compute compute compute compute compute compute compute_dt compute_fluxes compute_fluxes compute_fluxes_from_primitive compute_p23 compute_u23 compute_up23 compute_waves compute_waves compute_waves_u23 compute_waves_up23 cons_assign_cons cons_divide_real cons_multiply_cons cons_multiply_real conservative_compressible conservative_compressible_instance conservative_compressible_pointer conservative_to_primitive_compressible count count_substring cp create create create create create create create create create create create create create create create_ create_alpha_object create_alpha_object_constructor create_base_object_constructor create_beta_object create_beta_object_constructor create_constructor create_constructor create_constructor create_constructor create_constructor create_constructor create_interpolations_object create_interpolations_object_constructor create_interpolator create_interpolator_object create_interpolator_object_constructor create_kappa_object create_kappa_object_constructor create_weights_object create_weights_object_constructor ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P cv density description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_ dEuler_dt digit digit_I1 digit_I2 digit_I4 digit_I8 energy energy eos_compressible eos_compressible_instance errored errored errored euler_assign_euler euler_assign_real euler_local_error euler_multiply_euler euler_multiply_real finalize finalize finalize free free free free_object gam get_args_from_invocation get_args_from_string get_cla get_cla get_cla_from_buffer get_cla_list get_cla_list get_cla_list_from_buffer get_cla_list_varying_char get_cla_list_varying_char get_cla_list_varying_I1P get_cla_list_varying_I1P get_cla_list_varying_I2P get_cla_list_varying_I2P get_cla_list_varying_I4P get_cla_list_varying_I4P get_cla_list_varying_I8P get_cla_list_varying_I8P get_cla_list_varying_logical get_cla_list_varying_logical get_cla_list_varying_R16P get_cla_list_varying_R16P get_cla_list_varying_R4P get_cla_list_varying_R4P get_cla_list_varying_R8P get_cla_list_varying_R8P get_clasg_indexes impose_boundary_conditions init init init init init init init init init initialize initialize initialize initialize initialize initialize integrate integrate integrate integrate integrate integrate integrate integrate integrate interpolate_debug interpolate_debug interpolate_standard interpolate_standard is_admissible is_called_group is_defined is_defined is_defined_group is_parsed is_passed is_passed is_required_passed is_required_passed is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported left_eigenvectors max_stages max_stages max_stages max_stages_steps max_steps max_steps max_steps max_steps max_steps min_stages min_stages min_stages min_stages_steps min_steps min_steps min_steps min_steps min_steps momentum negative negative new_Dt output parse parse parse_command_line_interface penf_init penf_print positive positive pressure pressure prim_assign_prim prim_divide_real prim_multiply_prim prim_multiply_real primitive_compressible primitive_compressible_instance primitive_compressible_pointer primitive_to_conservative_compressible print_error_message print_usage print_version R raise_error_m_exclude raise_error_m_exclude raise_error_nargs_insufficient raise_error_switch_unknown raise_error_value_missing real_multiply_cons real_multiply_euler real_multiply_prim reconstruct_interfaces_characteristic reconstruct_interfaces_conservative reconstruct_interfaces_primitive replace replace_all riemann_solver_llf riemann_solver_pvl right_eigenvectors sanitize_defaults sanitize_defaults save_man_page save_time_serie save_usage_to_markdown set_mutually_exclusive_groups set_states14 signature signature signature smoothness_indicators solve solve solve_u23 solve_up23 speed_of_sound str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P style_index styles_samples sub sub sub_euler tau temperature tokenize tokenize unique update_previous update_previous update_previous upper upper_case usage usage usage used_registers velocity weno_exp weno_odd wenoof_create wstrip
Call graph
str calls strf_i4p, str_r4p, str_a_i4p, strf_i2p, strf_i1p, strf_r4p, str_a_r8p, strf_i8p, str_a_i2p, str_a_r4p, str_i4p, str_a_i1p, str_i2p, strf_r8p, str_i8p, str_a_i8p, str_bol, str_i1p, str_r8p
str_r4p calls compact_real_string
str_a_i4p calls str_i4p
str_a_r8p calls str_r8p
str_a_i2p calls str_i2p
str_a_r4p calls str_r4p
str_a_i1p calls str_i1p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string
check_choices calls str
description calls str
bctor_r16p calls str
bctoi_i2p calls str
errored calls str
save_time_serie calls str
foreseer_test_riemann_solver_compressible_llf calls str
bctor_r8p calls str
foreseer_test_riemann_solver_compressible_pvl calls str
usage calls str
bctoi_i4p calls str
bctoi_i8p calls str
foreseer_test_shock_tube calls str, save_time_serie
signature calls str
bctoi_i1p calls str
bctor_r4p calls str
bcton calls bctoi_i2p, bctor_r8p, bctoi_i4p, bctoi_i8p, bctoi_i1p, bctor_r4p